-- MySQL Script generated by MySQL Workbench
-- Tue Feb 20 11:38:39 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema semaphor151
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema semaphor151
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `semaphor151` DEFAULT CHARACTER SET utf8 ;
USE `semaphor151` ;

-- -----------------------------------------------------
-- Table `semaphor151`.`t_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `semaphor151`.`t_user` (
  `username` VARCHAR(20) NOT NULL,
  `password_hash` VARCHAR(60) NOT NULL,
  `isAdmin` TINYINT NOT NULL,
  `pk_user` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`pk_user`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `pk_user_UNIQUE` (`pk_user` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `semaphor151`.`t_room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `semaphor151`.`t_room` (
  `room_id` VARCHAR(20) NOT NULL,
  `pk_room` INT NOT NULL AUTO_INCREMENT,
  UNIQUE INDEX `idt_room_UNIQUE` (`room_id` ASC) VISIBLE,
  PRIMARY KEY (`pk_room`),
  UNIQUE INDEX `pk_room_UNIQUE` (`pk_room` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `semaphor151`.`t_message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `semaphor151`.`t_message` (
  `pk_message` INT NOT NULL AUTO_INCREMENT,
  `texte` VARCHAR(160) NOT NULL,
  `dateEnvoi` DATETIME NOT NULL,
  `fk_user` INT NOT NULL,
  `fk_room` INT NOT NULL,
  PRIMARY KEY (`pk_message`),
  UNIQUE INDEX `idt_message_UNIQUE` (`pk_message` ASC) VISIBLE,
  INDEX `fk_t_message_t_user1_idx` (`fk_user` ASC) VISIBLE,
  INDEX `fk_t_message_t_room1_idx` (`fk_room` ASC) VISIBLE,
  CONSTRAINT `fk_t_message_t_user1`
    FOREIGN KEY (`fk_user`)
    REFERENCES `semaphor151`.`t_user` (`pk_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_message_t_room1`
    FOREIGN KEY (`fk_room`)
    REFERENCES `semaphor151`.`t_room` (`pk_room`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
